sudo: required
services:
  - docker

before_install:
  - docker build -t aishwarydhare/docker-react -f Dockerfile.dev .

script:
  - docker run aishwarydhare/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "react-travis"
  env: "ReactTravis-env"
  bucket_name: "arn:aws:s3:::elasticbeanstalk-us-east-2-723547840476"
  bucket_path: "react-travis"
  on:
    branch: master
  access_key_id: "AKIAJZSQE4ZOZJPNGPLQ"
  secret_access_key: 
    secure: "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"
