sudo: required
services:
  - docker

before_install:
  - docker build -t aishwarydhare/docker-react -f Dockerfile.dev .

script:
  - docker run aishwarydhare/docker-react npm run test -- --coverage
  